address comments

diff --git a/configs/oumi/jobs/polaris/llama70b_eval.yaml b/configs/oumi/jobs/polaris/llama70b_eval.yaml
--- a/configs/oumi/jobs/polaris/llama70b_eval.yaml
+++ b/configs/oumi/jobs/polaris/llama70b_eval.yaml
@@ -11,6 +11,12 @@ resources:
 # Upload working directory to /home/$USER/oumi_launcher/llama70b_eval.
 working_dir: .
 
+envs:
+  # NOTE: For SFT, update this to point to your model checkpoint.
+  MODEL_CHECKPOINT_DIR: meta-llama/Meta-Llama-3.1-70B-Instruct
+  # NOTE: For LoRA, update this to point to your LoRA adapter.
+  LORA_ADAPTER_DIR: ""
+
 # `setup` will always be executed before `run`. It's strongly suggested to set any PBS
 # directives in the `setup` section. Additional commands can also be run here after the
 # PBS directives.
@@ -23,17 +29,18 @@ setup: |
   #PBS -e /eagle/community_ai/jobs/logs/
 
 run: |
-  set -e
-
-  # Various setup for running on Polaris.
+  set -e  # Exit if any command failed.
   source ${PBS_O_WORKDIR}/scripts/polaris/polaris_init.sh
 
-  # NOTE: For SFT, update this to point to your model checkpoint.
-  MODEL_CHECKPOINT_DIR="meta-llama/Meta-Llama-3.1-70B-Instruct"
-  # NOTE: For LoRA, update this to point to your LoRA adapter.
-  LORA_ADAPTER_DIR=""
+  if test ${OUMI_NUM_NODES} -ne 1; then
+    echo "LM Harness supports max 1 node. Actual: ${OUMI_NUM_NODES} nodes."
+    exit 1
+  fi
 
-  echo "Starting evaluation for ${EVAL_CHECKPOINT_DIR} ..."
+  echo "Starting evaluation for ${MODEL_CHECKPOINT_DIR} ..."
+  if test -n "$LORA_ADAPTER_DIR"; then
+    echo "Using LoRA adapter: ${LORA_ADAPTER_DIR}"
+  fi
 
   set -x # Enable command tracing.
   python -m oumi.evaluate \
