fix

diff --git a/configs/skypilot/sky_llama2b_ddp.yaml b/configs/skypilot/sky_llama2b_ddp.yaml
--- a/configs/skypilot/sky_llama2b_ddp.yaml
+++ b/configs/skypilot/sky_llama2b_ddp.yaml
@@ -24,12 +24,12 @@ setup: |
   pip install '.[gpu]'
 
 run: |
-  set -xe  # Exit if any command failed.
+  set -e  # Exit if any command failed.
   source ./configs/skypilot/sky_init.sh
 
   TOTAL_NUM_GPUS=$((${OUMI_NUM_NODES} * ${SKYPILOT_NUM_GPUS_PER_NODE}))
   ACCELERATE_MULTI_GPU_OPTION=
-  if [${TOTAL_NUM_GPUS} -gt 1]; then
+  if test ${TOTAL_NUM_GPUS} -gt 1; then
     ACCELERATE_MULTI_GPU_OPTION="--multi_gpu"
   fi
 
